#!/usr/bin/env Rscript
#generate overlap SNPs to do meta analysis

#_N files generated by Meta_Analysis.sh (adding sample size)
library(data.table)
#BE----
BEBonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BE_Bonn_autosomes_N.txt"))
BECambridge=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BE_Cambridge_autosomes_N.txt"))
BEOxford=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BE_oxford_autosomes_N.txt"))
comsnp=intersect(BEBonn$SNP,intersect(BECambridge$SNP,BEOxford$rsid))
#BEmeta=as.data.frame(fread("../result/Bonn_Oxford_Cambridge_METAANALYSIS_BE_1.tbl")) #includes snps from 3 data
idx=match(comsnp,BEBonn$SNP)
BEBonn_com=BEBonn[idx,]
idx=match(comsnp,BECambridge$SNP)
BECambridge_com=BECambridge[idx,]
idx=match(comsnp,BEOxford$rsid)
BEOxford_com=BEOxford[idx,]
fwrite(BEBonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BE_Bonn_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
fwrite(BECambridge_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BE_Cambridge_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
fwrite(BEOxford_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BE_oxford_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)

#EA---- #add Beacon, work on Beacon and Bonn
EABeacon=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_BEACON_autosomes_N.txt",fill=T))
EABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_autosomes_N.txt"))
EACambridge=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Cambridge_autosomes_N.txt"))
# comsnp=intersect(EABonn$SNP,EACambridge$SNP)
# comsnp=intersect(comsnp,EABeacon$SNP)
comsnp=intersect(EABonn$SNP,EABeacon$SNP)
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
# idx=match(comsnp,EACambridge$SNP)
# EACambridge_com=EACambridge[idx,]
idx=match(comsnp,EABeacon$SNP)
EABeacon_com=EABeacon[idx,]
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
# write.table(EACambridge_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Cambridge_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(EABeacon_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Beacon_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
#use high quality SNPs
idx1=which(EABeacon$info>=0.8)
idx2=which(EABonn$info>=0.8)
idx3=which(EACambridge$info>=0.8)
comsnp=intersect(EABonn$SNP[idx1],EACambridge$SNP[idx3])
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_BC_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
idx=match(comsnp,EACambridge$SNP)
EACambridge_com=EACambridge[idx,]
write.table(EACambridge_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Cambridge_BC_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
comsnp=intersect(EABeacon$SNP[idx1],EABonn$SNP[idx2])
idx=match(comsnp,EABeacon$SNP)
EABeacon_com=EABeacon[idx,]
write.table(EABeacon_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Beacon_BB_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_BB_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
#for Beacon genotyped without Amos
EABeacon=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/GWAS/Beacon_genotyped_EA_CO_gwas.assoc.logistic",fill=T))
EABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_autosomes_N.txt"))
comsnp=intersect(EABonn$SNP,EABeacon$SNP)
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
idx=match(comsnp,EABeacon$SNP)
EABeacon_com=EABeacon[idx,]
write.table(EABeacon_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Beacon_genotyped_BB_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_genotyped_BB_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)

#for Beacon imputed without Amos
EABeacon=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/GWAS/Beacon_EA_CO_gwas.assoc.logistic",fill=T))
EABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_autosomes_N.txt"))
comsnp=intersect(EABonn$SNP,EABeacon$SNP)
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
idx=match(comsnp,EABeacon$SNP)
EABeacon_com=EABeacon[idx,]
write.table(EABeacon_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Beacon_imp_BB_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_imp_BB_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)

#for Discovery genotyped
EADiscovery=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/GWAS/Discovery_genotyped_EA_CO_gwas.assoc.logistic",fill=T))
EABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_autosomes_N.txt"))
comsnp=intersect(EABonn$SNP,EADiscovery$SNP)
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
idx=match(comsnp,EADiscovery$SNP)
EADiscovery_com=EADiscovery[idx,]
write.table(EADiscovery_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Discovery_genotyped_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_genotyped_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)

BEEADiscovery=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/GWAS/Discovery_genotyped_BEEA_CO_gwas.assoc.logistic",fill=T))
BEEABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Bonn_autosomes_N.txt"))
comsnp=intersect(BEEABonn$SNP,BEEADiscovery$SNP)
idx=match(comsnp,BEEABonn$SNP)
BEEABonn_com=BEEABonn[idx,]
idx=match(comsnp,BEEADiscovery$SNP)
BEEADiscovery_com=BEEADiscovery[idx,]
write.table(BEEADiscovery_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Discovery_genotyped_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(BEEABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Bonn_genotyped_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)


#for Discovery imputped
EADiscovery=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/GWAS/Discovery_EA_CO_gwas.assoc.logistic",fill=T))
EABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_autosomes_N.txt"))
comsnp=intersect(EABonn$SNP,EADiscovery$SNP)
idx=match(comsnp,EABonn$SNP)
EABonn_com=EABonn[idx,]
idx=match(comsnp,EADiscovery$SNP)
EADiscovery_com=EADiscovery[idx,]
write.table(EADiscovery_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Discovery_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(EABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/EA_Bonn_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)

BEEADiscovery=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/GWAS/Discovery_BEEA_CO_gwas.assoc.logistic",fill=T))
BEEABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Bonn_autosomes_N.txt"))
comsnp=intersect(BEEABonn$SNP,BEEADiscovery$SNP)
idx=match(comsnp,BEEABonn$SNP)
BEEABonn_com=BEEABonn[idx,]
idx=match(comsnp,BEEADiscovery$SNP)
BEEADiscovery_com=BEEADiscovery[idx,]
write.table(BEEADiscovery_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Discovery_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
write.table(BEEABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Bonn_BD_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)

#BEEA----
BEEABonn=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Bonn_autosomes_N.txt"))
BEEACambridge=as.data.frame(fread("/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Cambridge_autosomes_N.txt"))
comsnp=intersect(BEEABonn$SNP,BEEACambridge$SNP)
idx=match(comsnp,BEEABonn$SNP)
BEEABonn_com=BEEABonn[idx,]
idx=match(comsnp,BEEACambridge$SNP)
BEEACambridge_com=BEEACambridge[idx,]
fwrite(BEEABonn_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Bonn_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
fwrite(BEEACambridge_com,file="/fh/fast/dai_j/BEACON/BEACON_GRANT/result/BEEA_Cambridge_autosomes_comsnp_N.txt",row.names = F,col.names = T,sep=" ",quote=F)
